"""initial schema

Revision ID: 2f7ea197035a
Revises: 
Create Date: 2026-05-08 19:32:39.015681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f7ea197035a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=False),
    sa.Column('last_facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_ipv4', sa.String(length=45), sa.Computed("json_extract(last_facts, '$.ansible_default_ipv4.address')", persisted=True), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), sa.Computed("json_extract(last_facts, '$.ansible_uptime_seconds')", persisted=True), nullable=True),
    sa.Column('virt_role', sa.String(length=16), sa.Computed("json_extract(last_facts, '$.ansible_virtualization_role')", persisted=True), nullable=True),
    sa.Column('virt_type', sa.String(length=32), sa.Computed("json_extract(last_facts, '$.ansible_virtualization_type')", persisted=True), nullable=True),
    sa.Column('memtotal_mb', sa.Integer(), sa.Computed("json_extract(last_facts, '$.ansible_memtotal_mb')", persisted=True), nullable=True),
    sa.Column('vcpus', sa.Integer(), sa.Computed("json_extract(last_facts, '$.ansible_processor_vcpus')", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_fqdn'), ['fqdn'], unique=True)
        batch_op.create_index(batch_op.f('ix_hosts_last_seen_at'), ['last_seen_at'], unique=False)

    op.create_table('playbooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('inventory_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'FINISHED', 'FAILED', name='playbook_status'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('skip_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limit', sa.String(length=512), nullable=True),
    sa.Column('check_mode', sa.Boolean(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_started_at'), ['started_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_uuid', sa.Uuid(), nullable=False),
    sa.Column('playbook_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=512), nullable=False),
    sa.Column('task_action', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('OK', 'CHANGED', 'FAILED', 'UNREACHABLE', 'SKIPPED', name='task_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stdout_truncated', sa.Boolean(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uuid', name='uq_events_event_uuid')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_uuid'), ['event_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_playbook_id'), ['playbook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_started_at'), ['started_at'], unique=False)

    op.create_table('host_facts_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('playbook_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('host_facts_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_host_facts_history_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_facts_history_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_facts_history_playbook_id'), ['playbook_id'], unique=False)

    op.create_table('playbook_hosts',
    sa.Column('playbook_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('inventory_hostname', sa.String(length=255), nullable=False),
    sa.Column('groups', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playbook_id', 'host_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playbook_hosts')
    with op.batch_alter_table('host_facts_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_host_facts_history_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_host_facts_history_host_id'))
        batch_op.drop_index(batch_op.f('ix_host_facts_history_captured_at'))

    op.drop_table('host_facts_history')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_started_at'))
        batch_op.drop_index(batch_op.f('ix_events_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_events_host_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_uuid'))

    op.drop_table('events')
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbooks_started_at'))

    op.drop_table('playbooks')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_hosts_fqdn'))

    op.drop_table('hosts')
    # ### end Alembic commands ###
